# Generated by Django 4.2.26 on 2025-11-22 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_category_store'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
