# Generated by Django 4.2.15 on 2025-11-03 08:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pointstransaction',
            options={'verbose_name': 'عملية نقاط', 'verbose_name_plural': 'عمليات النقاط'},
        ),
        migrations.AlterField(
            model_name='pointstransaction',
            name='amount',
            field=models.IntegerField(verbose_name='القيمة (موجبة للإضافة وسالبة للخصم)'),
        ),
        migrations.AlterField(
            model_name='pointstransaction',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ العملية'),
        ),
        migrations.AlterField(
            model_name='pointstransaction',
            name='extra_data',
            field=models.TextField(blank=True, null=True, verbose_name='بيانات إضافية'),
        ),
        migrations.AlterField(
            model_name='pointstransaction',
            name='note',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ملاحظات'),
        ),
        migrations.AlterField(
            model_name='pointstransaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم'),
        ),
    ]
