# Generated by Django 4.2.15 on 2025-11-06 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_pointstransaction_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointstransaction',
            name='amount',
            field=models.IntegerField(verbose_name='القيمة (موجب للإضافة، سالب للخصم)'),
        ),
    ]
