# Generated by Django 4.2.15 on 2025-11-26 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_pointstransaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointstransaction',
            name='transaction_type',
            field=models.CharField(choices=[('add', 'إضافة نقاط'), ('subtract', 'سحب نقاط'), ('adjust', 'تعديل الرصيد')], max_length=10),
        ),
    ]
