# Generated by Django 4.2.15 on 2025-11-30 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='item_note',
            field=models.TextField(blank=True, null=True, verbose_name='ملاحظات المنتج'),
        ),
    ]
