# Generated by Django 4.2.15 on 2025-11-26 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='description2',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='store',
            name='description3',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='store',
            name='description4',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='store',
            name='description5',
            field=models.TextField(blank=True),
        ),
    ]
