# Generated by Django 4.2.15 on 2025-12-04 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0003_storepaymentmethod'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='allow_cash_on_delivery',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='store',
            name='allow_full_payment',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='store',
            name='allow_partial_payment',
            field=models.BooleanField(default=False),
        ),
    ]
