# Generated by Django 4.2.15 on 2025-12-04 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0004_store_allow_cash_on_delivery_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='payment_required_percentage',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
