# Generated by Django 4.2.15 on 2025-11-06 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laptop', '0013_product_price_purchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessoryl',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='accessorym',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='laptop',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
