# Generated by Django 4.2.15 on 2025-11-06 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laptop', '0014_accessoryl_available_accessorym_available_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessoryl',
            name='code',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='الرقم التسلسلي'),
        ),
        migrations.AddField(
            model_name='accessorym',
            name='code',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='الرقم التسلسلي'),
        ),
        migrations.AddField(
            model_name='laptop',
            name='code',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='الرقم التسلسلي'),
        ),
        migrations.AddField(
            model_name='product',
            name='code',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='الرقم التسلسلي'),
        ),
    ]
