# Generated by Django 4.2.26 on 2025-11-23 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='transaction_type',
            field=models.CharField(choices=[('sale', 'بيع'), ('purchase', 'شراء')], default='sale', max_length=10),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='direction',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
