# Generated by Django 4.2.15 on 2025-11-30 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_order_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='item_note',
            field=models.TextField(blank=True, null=True, verbose_name='ملاحظات المنتج'),
        ),
    ]
