# Generated by Django 4.2.15 on 2025-12-03 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0003_storepaymentmethod'),
        ('orders', '0006_orderitem_item_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_account_info',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_additional_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders_payment', to='stores.storepaymentmethod'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method_name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_recipient_name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
