# Generated by Django 4.2.15 on 2025-12-04 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_order_shipping_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_type',
            field=models.CharField(blank=True, choices=[('full', 'تحويل كامل'), ('partial', 'دفعة مسبقة + باقي عند التسليم'), ('cod', 'الدفع عند الاستلام')], max_length=20, null=True),
        ),
    ]
