# Generated by Django 4.2.15 on 2025-12-04 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_order_payment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_proof_image',
            field=models.ImageField(blank=True, null=True, upload_to='payments/'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_transaction_id',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
