# Generated by Django 4.2.15 on 2025-12-08 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_order_payment_proof_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_seen_by_store',
            field=models.BooleanField(default=False),
        ),
    ]
