# Generated by Django 4.2.15 on 2025-12-10 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_order_is_seen_by_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='buy_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='تكلفة القطعة وقت البيع / سعر الشراء', max_digits=10, null=True),
        ),
    ]
