# Generated by Django 4.2.15 on 2025-12-10 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_category2'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='buy_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='متوسط سعر شراء المنتج', max_digits=10),
        ),
    ]
